import React from 'react'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Head from 'next/head'

function Myaccount() {
  const router = useRouter()
  useEffect(() => {
  
   if(!localStorage.getItem('token')){
    router.push('/')
   }
  },)
  
  return (
    
    <div>
         <Head>
        <title>LOCOCART - Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href="/logo.png" />
      </Head>Myaccount</div>
  )
}

export default Myaccount