import React from "react";

import axios from "axios";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Link from "next/link";
import Head from "next/head";
const Orders = () => {
  const [order, setorder] = useState([]);


  const router = useRouter();
  useEffect(() => {
    const fetchorders = async () => {
      const { data } = await axios.post(
        `${process.env.VERCEL_URL || "http://localhost:3000"}/api/myorders`,
        {
          token: localStorage.getItem("token"),
        }
      );
     setorder(data.orders)
    };
    if (!localStorage.getItem("token")) {
      router.push("/");
    } else {
      fetchorders();
    }
  });
  return (
    <>
      <Head>
        <title>LOCOCART - Orders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="png" href="/logo.png" />
      </Head>
      <div className="mx-auto md:mx-10 min-h-screen">
        <div className="flex flex-col">
          <div className="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div className="inline-block min-w-full py-2 sm:px-6 lg:px-8">
              <div className="overflow-hidden">
                <h1 className="font-bold text-lg text-center p-4">My Orders</h1>
                <table className="min-w-full text-left text-sm font-light">
                  <thead className="border-b font-medium dark:border-pink-500">
                    <tr className="bg-pink-600 text-white">
                      <th scope="col" className="px-6 py-4">
                        #Order Id
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Email
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Amount
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Order Date
                      </th>
                      <th scope="col" className="px-6 py-4">
                        Details
                      </th>
                    </tr>
                  </thead>
                  <tbody className="text-slate-700 font-semibold">
                    {order.map(
                      (item, i) =>
                        item.status === "paid" && (
                          <tr
                            key={i}
                            className="border-b transition duration-300 ease-in-out hover:bg-pink-100 border-pink-500 "
                          >
                            <td className="whitespace-nowrap px-6 py-4 font-medium">
                              {item._id}
                            </td>
                            <td className="whitespace-nowrap px-6 py-4">
                              {item.email}
                            </td>

                            <td className="whitespace-nowrap  px-6 py-4">
                              ₹{item.amount}
                            </td>
                            <td className="whitespace-nowrap px-6 py-4">
                              {item.createdAt && new Date(item.createdAt).toLocaleString("en-IN")}
                            </td>
                            <td className="whitespace-nowrap px-6 py-4">
                              <Link
                                className="cursor-pointer hover:underline"
                                href={`/Order/?id=${item._id}`}
                              >
                                See Details
                              </Link>
                            </td>
                          </tr>
                        )
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Orders;
